// <auto-generated />
using System;
using ChasmaWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChasmaWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613163130_Forgot-Password-Migration")]
    partial class ForgotPasswordMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ChasmaWebApi.Data.Models.RepositoryModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<int>("HostPlatform")
                        .HasColumnType("INTEGER")
                        .HasColumnName("remote_host_platform");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_ignored");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.ToTable("repositories");
                });

            modelBuilder.Entity("ChasmaWebApi.Data.Models.RepositoryWorkContextSnapshotModel", b =>
                {
                    b.Property<int>("DatabaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("database_id");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("branch_name");

                    b.Property<string>("CommitHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("commit_hash");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("IntentNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("intent_note");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_id");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("StashMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("stash_message");

                    b.HasKey("DatabaseId");

                    b.ToTable("repository_snapshots");
                });

            modelBuilder.Entity("ChasmaWebApi.Data.Models.UserAccountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstSecurityAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_security_answer");

                    b.Property<byte[]>("FirstSecurityAnswerSalt")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("first_security_answer_salt");

                    b.Property<string>("FirstSecurityQuestion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_security_question");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("refreshToken");

                    b.Property<DateTime>("RefreshTokenExpiration")
                        .HasColumnType("TEXT")
                        .HasColumnName("refreshTokenExpiration");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("salt");

                    b.Property<string>("SecondSecurityAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("second_security_answer");

                    b.Property<byte[]>("SecondSecurityAnswerSalt")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("second_security_answer_salt");

                    b.Property<string>("SecondSecurityQuestion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("second_security_question");

                    b.Property<string>("ThirdSecurityAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("third_security_answer");

                    b.Property<byte[]>("ThirdSecurityAnswerSalt")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("third_security_answer_salt");

                    b.Property<string>("ThirdSecurityQuestion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("third_security_question");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("user_accounts");
                });

            modelBuilder.Entity("ChasmaWebApi.Data.Models.WorkContextSnapshotModel", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("SnapshotNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_note");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("SnapshotId");

                    b.ToTable("work_context_snapshots");
                });

            modelBuilder.Entity("ChasmaWebApi.Data.Models.WorkingDirectoryModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_id");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("working_directory");

                    b.HasKey("Id");

                    b.ToTable("working_directories");
                });
#pragma warning restore 612, 618
        }
    }
}
