#!/bin/bash
set -e

if [ ! -d "/var/lib/Emryce" ]; then
    mkdir -p /var/lib/Emryce
fi

chmod 777 /var/lib/Emryce
chmod +x /opt/emryce/ChasmaWebApi
ln -sf /opt/emryce/ChasmaWebApi /usr/bin/emryce
update-desktop-database -q
exit 0