# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ChasmaWebApi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ".\ChasmaWebApi\ChasmaWebApi.csproj"
    - name: Build Web API
      run: dotnet build ".\ChasmaWebApi\ChasmaWebApi.csproj" --no-restore
    - name: Test Web API
      run: dotnet test ".\ChasmaWebApi\ChasmaWebApi.csproj" --no-build --verbosity normal
